project_id = "suifjjqssfbercvhicrn"

[functions.send-invitation]
verify_jwt = false

[functions.generate-report]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.sync-interviews]
verify_jwt = true

[functions.automated-alerts]
verify_jwt = false