// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suifjjqssfbercvhicrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aWZqanFzc2ZiZXJjdmhpY3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDEyNzksImV4cCI6MjA3MjQ3NzI3OX0.dvjc_V9EuzYvPoOx_Z3gS5gZwCr7-Y81HiCei6-Cek0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});